
name: distlib # you probably want to 'snapcraft register <name>'
version: '0.6.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Library of C++ utilities for Distributed Systems.
description: |
  A set of libraries and utilities that support the development
  of distributed systems.
  Consistent hashing, Merkle trees, Gossip Protocol failure detectors, and
  ZMQ-based client/server implementations.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil
